CREATE TABLE IF NOT EXISTS usuarios (
 Id INT AUTO_INCREMENT PRIMARY KEY, Nome VARCHAR(100) NOT NULL, Email VARCHAR(190) NOT NULL UNIQUE,
 SenhaHash VARCHAR(100) NOT NULL, Telefone VARCHAR(30), DataNascimento DATE, TrocarSenha BOOLEAN NOT NULL DEFAULT 0,
 DataInclusao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, DataAlteracao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS receitas (
 Id INT AUTO_INCREMENT PRIMARY KEY, UsuarioId INT NOT NULL, Descricao VARCHAR(150) NOT NULL, Categoria VARCHAR(50) NOT NULL,
 Valor DECIMAL(18,2) NOT NULL, Periodicidade VARCHAR(20) NOT NULL, Data DATE NOT NULL, Ativo BOOLEAN NOT NULL DEFAULT 1, Fixa BOOLEAN NOT NULL DEFAULT 1,
 DataInclusao DATETIME DEFAULT CURRENT_TIMESTAMP, DataAlteracao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (UsuarioId) REFERENCES usuarios(Id), INDEX (UsuarioId,Data)
);
CREATE TABLE IF NOT EXISTS despesas (
 Id INT AUTO_INCREMENT PRIMARY KEY, UsuarioId INT NOT NULL, Descricao VARCHAR(150) NOT NULL, Categoria VARCHAR(50) NOT NULL,
 Valor DECIMAL(18,2) NOT NULL, Periodicidade VARCHAR(20) NOT NULL, Data DATE NOT NULL, Ativo BOOLEAN NOT NULL DEFAULT 1, Fixa BOOLEAN NOT NULL DEFAULT 1,
 DataInclusao DATETIME DEFAULT CURRENT_TIMESTAMP, DataAlteracao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (UsuarioId) REFERENCES usuarios(Id), INDEX (UsuarioId,Data)
);
CREATE TABLE IF NOT EXISTS dividas (
 Id INT AUTO_INCREMENT PRIMARY KEY, UsuarioId INT NOT NULL, Descricao VARCHAR(150) NOT NULL, Credor VARCHAR(100) NOT NULL,
 ValorTotal DECIMAL(18,2) NOT NULL, ValorParcela DECIMAL(18,2) NOT NULL, QuantidadeParcelas INT NOT NULL, ParcelasPagas INT NOT NULL DEFAULT 0,
 DataInicio DATE NOT NULL, DataInclusao DATETIME DEFAULT CURRENT_TIMESTAMP, DataAlteracao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (UsuarioId) REFERENCES usuarios(Id)
);
CREATE TABLE IF NOT EXISTS objetivos (
 Id INT AUTO_INCREMENT PRIMARY KEY, UsuarioId INT NOT NULL, Nome VARCHAR(100) NOT NULL, Descricao VARCHAR(1000), Categoria VARCHAR(50) NOT NULL,
 Icone VARCHAR(40) NOT NULL, ValorObjetivo DECIMAL(18,2) NOT NULL, ValorInicial DECIMAL(18,2) NOT NULL DEFAULT 0,
 DataInicio DATE NOT NULL, DataLimite DATE NOT NULL, Frequencia VARCHAR(20) NOT NULL, Status VARCHAR(20) NOT NULL DEFAULT 'Ativo', Prioridade INT NOT NULL DEFAULT 2,
 DataConclusao DATE, DataInclusao DATETIME DEFAULT CURRENT_TIMESTAMP, DataAlteracao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (UsuarioId) REFERENCES usuarios(Id), INDEX (UsuarioId,Status)
);
CREATE TABLE IF NOT EXISTS contribuicoes_objetivos (
 Id INT AUTO_INCREMENT PRIMARY KEY, ObjetivoId INT NOT NULL, Valor DECIMAL(18,2) NOT NULL, Data DATE NOT NULL, Observacao VARCHAR(500),
 DataInclusao DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (ObjetivoId) REFERENCES objetivos(Id) ON DELETE CASCADE, INDEX (ObjetivoId,Data)
);
CREATE TABLE IF NOT EXISTS historico_objetivos (
 Id INT AUTO_INCREMENT PRIMARY KEY, ObjetivoId INT NOT NULL, Descricao VARCHAR(1000) NOT NULL,
 DataInclusao DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (ObjetivoId) REFERENCES objetivos(Id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS categorias (
 Id INT AUTO_INCREMENT PRIMARY KEY, Nome VARCHAR(50) NOT NULL UNIQUE, DataInclusao DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS notificacoes (
 Id INT AUTO_INCREMENT PRIMARY KEY, UsuarioId INT NOT NULL, Mensagem VARCHAR(500) NOT NULL, Lida BOOLEAN DEFAULT 0,
 DataInclusao DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (UsuarioId) REFERENCES usuarios(Id)
);
CREATE TABLE IF NOT EXISTS configuracoes_usuario (
 Id INT AUTO_INCREMENT PRIMARY KEY, UsuarioId INT NOT NULL UNIQUE, Moeda VARCHAR(3) DEFAULT 'BRL', FormatoData VARCHAR(20) DEFAULT 'dd/MM/yyyy',
 PrimeiroDiaSemana INT DEFAULT 0, Notificacoes BOOLEAN DEFAULT 1, DataInclusao DATETIME DEFAULT CURRENT_TIMESTAMP,
 DataAlteracao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (UsuarioId) REFERENCES usuarios(Id)
);
